<pre class="metadata">
Title: CSS Route Matching
Status: UD
Work Status: Exploring
Shortname: css-route-matching
Org: w3c
Level: 1
Repository: WICG/declarative-route-matching
!Issue Tracking: <a href="https://github.com/w3c/csswg-drafts/issues/12594">w3c/csswg-drafts#12594</a>
ED: https://wicg.github.io/declarative-partial-updates/css-route-matching/
Editor: L. David Baron, Google https://www.google.com/, https://dbaron.org/, w3cid 15393
Editor: Noam Rosenthal, Google https://www.google.com/, w3cid 121539
No Abstract: true
Boilerplate: references no, status no, conformance no
</pre>

This specification has moved to
<a href="https://drafts.csswg.org/css-navigation-1/">https://drafts.csswg.org/css-navigation-1/</a>.
