name: Automatic Publication

on:
  pull_request: {}
  push:
    branches: [main]

jobs:
  validate-and-publish:
    name: Build, Validate, and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: bikeshed
          GH_PAGES_BRANCH: gh-pages
          SOURCE: css-route-matching/index.bs

